"""Opt-in pytest plugin: per-fixture setup timing.

pytest core has no per-fixture timer. A ``setup`` row in ``--durations`` is the
whole setup chain for one test item, and a shared higher-scope fixture is billed
to the first item that triggers it. This plugin wraps ``pytest_fixture_setup`` to
attribute setup cost to the *individual* fixture, then prints the slowest
fixtures (aggregated by name + scope) in the terminal summary -- filling the one
gap the stock durations table cannot.

Generated by pytest-optimizer as a project-owned helper. Use it either by
importing it from a ``conftest.py`` via ``pytest_plugins``, or by registering it
under ``[project.entry-points.pytest11]``. Gitignore it unless you choose to
commit it. Remove it once you have the timings you need -- it adds a small
per-fixture overhead.

Notes
-----
- Only cache *misses* are timed: pytest reuses a fixture's ``cached_result``
  within its scope, so a session-scoped fixture is timed once.
- Under xdist each worker aggregates and prints its own table; read them per
  worker or run serially while profiling.
"""

from __future__ import annotations

import time
import typing as t
from collections import defaultdict

import pytest

if t.TYPE_CHECKING:
    from _pytest.fixtures import FixtureDef, SubRequest
    from _pytest.terminal import TerminalReporter


# (fixture_name, scope) -> list of per-setup wall seconds
_TIMINGS: dict[tuple[str, str], list[float]] = defaultdict(list)


@pytest.hookimpl(hookwrapper=True)
def pytest_fixture_setup(
    fixturedef: FixtureDef[t.Any],
    request: SubRequest,
) -> t.Generator[None, t.Any, None]:
    """Record the wall time of one fixture's setup.

    ``hookwrapper`` is used (rather than the newer ``wrapper``) so the same file
    works on pytest 6 through 9.
    """
    start = time.perf_counter()
    yield
    elapsed = time.perf_counter() - start
    _TIMINGS[(fixturedef.argname, str(fixturedef.scope))].append(elapsed)


def pytest_terminal_summary(
    terminalreporter: TerminalReporter,
    exitstatus: int,
    config: pytest.Config,
) -> None:
    """Print the slowest fixtures by total setup time."""
    if not _TIMINGS:
        return

    limit = int(config.getini("optimizer_fixture_timing_limit") or 20)
    rows = [
        (sum(samples), len(samples), name, scope)
        for (name, scope), samples in _TIMINGS.items()
    ]
    rows.sort(reverse=True)  # by total time descending

    tr = terminalreporter
    tr.write_sep("=", "slowest fixtures (setup, by total time)")
    tr.write_line(f"{'total':>8}  {'n':>4}  {'each':>8}  scope     fixture")
    for total, count, name, scope in rows[:limit]:
        each = total / count if count else 0.0
        tr.write_line(
            f"{total:8.3f}  {count:4d}  {each:8.3f}  {scope:<8}  {name}"
        )


def pytest_addoption(parser: pytest.Parser) -> None:
    """Register the limit ini so projects can widen/narrow the table."""
    parser.addini(
        "optimizer_fixture_timing_limit",
        help="Max rows in the slowest-fixtures table (default 20).",
        default="20",
    )
